### ISSUE TITLE
why does every function call return *this?

### ISSUE THREAD

**Issue by sticilface** [arcao/Syslog#2]
This is great for the setup functions, but I was wondering if a bool for message sent might be more helpful for the sending of messages.  That way you know if it was sent, or if it returned because of an error.  

There is no way of checking that everything has been configured correctly at the moment ?

Good lib BTW.

**Comment by arcao** [comment]
You are right. I will change it in version 3.0.

**Comment by sticilface** [comment]
Cool cheers :)

**Comment by arcao** [comment]
Fixed.
