### ISSUE TITLE
Mixing Strings and F()?

### ISSUE THREAD

**Issue by MarcFinns** [arcao/Syslog#7]
Hello, I see that you support the F() macro.
However, in some cases it would be great to be able to mix. For example:
log("X value is " + String(X));
The statement above fails. When logging on serial i can work around the issue by having separate print + println for the two, but i cant do it with systlog.
any hint? thanks!

**Comment by arcao** [comment]
Try this:

```cpp
syslog.logf_P(PSTR("X value is %d"), X);
```

**Comment by MarcFinns** [comment]
Arcao, this works for %d. What can be done for Strings?
I mean, concatenating a constant portion and a variable. I tries %s but does not work.
thanks
